/*
Evan Hansen
06/07/18
A form that opens which presents the user with a message informing them of their death.
This will record a high score of their level and progress and give the player
an opportunity to start from the beginning
It will also play music to enhance the feeling of their passing

 */
package gertrogan;

import java.awt.event.*;
import java.io.*;
import javax.sound.sampled.*;


/*
To-do
>New form displaying an image...Done!
>Music playing on a loop...
>Save player's progress to a data file...
 */
public class Death extends javax.swing.JFrame implements KeyListener {
    private Clip clip;
    private TitleMenu titleMenu;
    private HighScore score;

    public Death(int stage, int level, int enemiesKilled) {
        initComponents();
        setFocusable(true);
        this.addKeyListener(this);
        
        score = new HighScore("Adam", (stage * level * enemiesKilled));
        System.out.println(score.getHighScores());
        score.addHighScore();
        System.out.println(score.getHighScores());
        try {
         // Open an audio input stream.
            File soundFile = new File("src\\gertrogan\\Death Music.wav");
            AudioInputStream audioIn = AudioSystem.getAudioInputStream(soundFile);
         // Get a sound clip resource.
            clip = AudioSystem.getClip();
         // Open audio clip and load samples from the audio input stream.
            clip.open(audioIn);
            clip.loop(Clip.LOOP_CONTINUOUSLY);
      } catch (UnsupportedAudioFileException e) {
            e.printStackTrace();
      } catch (IOException e) {
            e.printStackTrace();
      } catch (LineUnavailableException e) {
            e.printStackTrace();
      }
    }
//---------------------------------------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gertrogan - You died ;-;");
        setMinimumSize(new java.awt.Dimension(800, 800));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Viner Hand ITC", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Press any key to continue");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 560, 430, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gertrogan/death.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 800);

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(410, 560, 41, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents
//----------------------------------------------------------------------------------------------

    //no work need fix
    

    public void keyPressed(KeyEvent e) {
        
        titleMenu = new TitleMenu();
        titleMenu.setVisible(true);
        this.setVisible(false);
        if (clip.isRunning()) clip.stop();
    }

    public void keyTyped(KeyEvent e) {
        //not needed
    }

    public void keyReleased(KeyEvent e) {
        //not needed
    }

    /**
     * @param args the command line arguments
     */
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
